"""End-to-end ASR smoke through a running AdVera stack (synthetic audio only).

For each file generated by scripts/make_smoke_audio.py: create a meeting, import the file,
wait for the durable transcription job, and check the definitive transcript against the
expected languages and, with --speakers, the expected number of distinct speakers.
Every run includes Catalan (spec §7, §25).

Usage: python scripts/asr_smoke.py [--api http://localhost:18000] [--speakers] [--show-text]
"""

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SMOKE = ROOT / "data" / "smoke"

# Known provider limitations: reported as XFAIL (and XPASS if they start passing) so the smoke
# stays honest without hiding regressions elsewhere.
KNOWN_ISSUES = {
    "es-en-two-speakers.wav": "WhisperX detects one language per track and drops the other "
    "language's speech (docs/features/rebuild-local-diarization.md, risks)",
}

# file -> (accepted primary languages, expected distinct speakers, words that must appear)
EXPECTATIONS = {
    "ca-single.wav": ({"ca"}, 1, ["tothom", "divendres"]),
    "ca-two-speakers.wav": ({"ca"}, 2, ["calendari", "pressupost"]),
    "es-single.wav": ({"es"}, 1, ["calendario", "lunes"]),
    "en-single.wav": ({"en"}, 1, ["release", "budget"]),
    # Both languages must survive: the Spanish and the English lines.
    "es-en-two-speakers.wav": ({"es", "en"}, 2, ["publicamos", "release"]),
}


def call(api: str, method: str, path: str, body: bytes | None = None, headers=None):
    request = urllib.request.Request(api + path, data=body, method=method, headers=headers or {})
    with urllib.request.urlopen(request, timeout=600) as response:
        return json.loads(response.read() or b"null")


def run_file(api: str, source: Path, check_speakers: bool, show_text: bool) -> bool:
    languages, speakers, words = EXPECTATIONS[source.name]
    meeting = call(
        api,
        "POST",
        "/api/meetings",
        json.dumps({"title": f"Smoke {source.stem}"}).encode(),
        {"Content-Type": "application/json"},
    )
    boundary = uuid.uuid4().hex
    payload = (
        (
            f'--{boundary}\r\nContent-Disposition: form-data; name="file"; filename="{source.name}"\r\n'
            "Content-Type: audio/wav\r\n\r\n"
        ).encode()
        + source.read_bytes()
        + f"\r\n--{boundary}--\r\n".encode()
    )
    started = time.monotonic()
    call(
        api,
        "POST",
        f"/api/meetings/{meeting['id']}/imports",
        payload,
        {"Content-Type": f"multipart/form-data; boundary={boundary}"},
    )
    while True:
        status = call(api, "GET", f"/api/meetings/{meeting['id']}/transcription")
        if status["status"] in ("completed", "failed"):
            break
        time.sleep(2)
    elapsed = time.monotonic() - started
    if status["status"] != "completed":
        print(
            f"FAIL {source.name}: job {status['status']} error={status['error']} ({elapsed:.0f}s)"
        )
        return False

    detail = call(api, "GET", f"/api/meetings/{meeting['id']}")
    transcript = call(api, "GET", f"/api/meetings/{meeting['id']}/transcript")
    found_languages = set(detail["primary_language"])
    found_speakers = detail["attendee_count"]
    text = " ".join(segment["text"].lower() for segment in transcript["segments"])
    missing = [word for word in words if word not in text]
    ok = bool(found_languages) and found_languages <= languages and not missing
    if check_speakers:
        ok = ok and found_speakers == speakers
    provenance = transcript["provenance"]["tracks"][0]
    known = KNOWN_ISSUES.get(source.name)
    verdict = ("XPASS" if ok else "XFAIL") if known else ("PASS" if ok else "FAIL")
    print(
        f"{verdict} {source.name}: {elapsed:.0f}s languages={sorted(found_languages)} "
        f"speakers={found_speakers} (expected {speakers}) segments={len(transcript['segments'])} "
        f"provider={provenance['provider']}/{provenance['model']}"
        + (f" missing={missing}" if missing else "")
        + ("\n    known issue: " + known if known and not ok else "")
    )
    if show_text:
        for segment in transcript["segments"]:
            print(
                f"    [{segment['start']:6.2f}-{segment['end']:6.2f}] "
                f"{segment['speaker'] or '-':>10} {segment['language']}: {segment['text']}"
            )
    return ok or bool(known)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--api", default="http://localhost:18000")
    parser.add_argument("--speakers", action="store_true", help="also check speaker counts")
    parser.add_argument("--show-text", action="store_true", help="print synthetic transcripts")
    args = parser.parse_args()

    files = [SMOKE / name for name in EXPECTATIONS if (SMOKE / name).is_file()]
    if not any(path.name.startswith("ca-") for path in files):
        print("Catalan smoke audio is missing: run scripts/make_smoke_audio.py", file=sys.stderr)
        return 1
    try:
        results = [run_file(args.api, path, args.speakers, args.show_text) for path in files]
    except urllib.error.URLError as error:
        print(f"API unavailable: {error}", file=sys.stderr)
        return 1
    print(f"{sum(results)}/{len(results)} passed")
    return 0 if all(results) else 1


if __name__ == "__main__":
    sys.exit(main())
